package com.samsonmedia.barn.cli;

import picocli.AutoComplete;
import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Model.CommandSpec;
import picocli.CommandLine.Option;
import picocli.CommandLine.Spec;

/**
 * Command to generate shell autocompletion scripts.
 *
 * <p>Usage:
 * <pre>
 * # Generate and install bash completion
 * barn autocompletion --bash &gt; /usr/local/etc/bash_completion.d/barn
 *
 * # Generate and install zsh completion
 * barn autocompletion --zsh &gt; ~/.zsh/completions/_barn
 * </pre>
 */
@Command(
    name = "autocompletion",
    mixinStandardHelpOptions = true,
    description = "Generate shell autocompletion scripts"
)
public class AutocompletionCommand implements Runnable {

    @Spec
    private CommandSpec spec;

    @Option(names = {"--bash"}, description = "Generate bash completion script")
    private boolean bash;

    @Option(names = {"--zsh"}, description = "Generate zsh completion script")
    private boolean zsh;

    @Override
    public void run() {
        if (!bash && !zsh) {
            spec.commandLine().usage(spec.commandLine().getOut());
            return;
        }

        // Get the root command
        CommandLine rootCmd = spec.commandLine().getParent();
        if (rootCmd == null) {
            rootCmd = spec.commandLine();
        }

        String script = AutoComplete.bash(
            rootCmd.getCommandName(),
            rootCmd
        );

        if (zsh) {
            // Wrap bash completion for zsh compatibility
            script = generateZshCompletion(rootCmd.getCommandName(), script);
        }

        spec.commandLine().getOut().println(script);
    }

    private String generateZshCompletion(String name, String bashScript) {
        StringBuilder sb = new StringBuilder();
        sb.append("#compdef ").append(name).append("\n\n");
        sb.append("# Zsh completion for ").append(name).append("\n");
        sb.append("# Generated by barn autocompletion --zsh\n\n");
        sb.append("autoload -U +X bashcompinit && bashcompinit\n\n");
        sb.append(bashScript);
        return sb.toString();
    }
}
